<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="<?php echo asset('/css/app.css'); ?>">
</head>
<body>
	<div class="container mt-5">
		<div id="profile">
			<div class="form-floating mb-3">
				<input type="text" class="form-control" id="name" placeholder="Enter name" name="name" value="Kir">
				<label for="name">Enter name</label>
			</div>
			<div class="form-floating mb-3">
				<input type="text" class="form-control" id="surname" placeholder="Enter surname" name="surname" value="Cal">
				<label for="surname">Enter surname</label>
			</div>
			<div class="form-floating mb-3">
				<select class="form-select" id="floatingSelect" aria-label="Floating label select example" name="city">
					<option disabled>Open this select menu</option>
					<option value="1" selected>One</option>
					<option value="2">Two</option>
					<option value="3">Three</option>
				</select>
				<label for="floatingSelect">Works with selects</label>
			</div>
			<div class="btn-group btn-group-lg d-flex mb-3" role="group" aria-label="Basic checkbox toggle button group">
				<input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off" name="lang[]" value="PHP" checked>
				<label class="btn btn-outline-primary" for="btncheck1">PHP</label>

				<input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off" name="lang[]" value="JS" checked>
				<label class="btn btn-outline-warning" for="btncheck2">JS</label>

				<input type="checkbox" class="btn-check" id="btncheck3" autocomplete="off" name="lang[]" value="C++">
				<label class="btn btn-outline-info" for="btncheck3">C++</label>
			</div>
			<div class="form-floating mb-3">
				<textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea" name="comment">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime perferendis nesciunt omnis aperiam corrupti, ex voluptas obcaecati, vitae commodi eius dolorem nam perspiciatis aut placeat, velit reprehenderit eaque reiciendis, fuga.</textarea>
				<label for="floatingTextarea">Comments</label>
			</div>
			<div class="mb-3">
				<input class="form-control form-control-lg" type="file" name="photo">
			</div>
			<div class="d-grid gap-2">
				<button class="btn btn-success btn-block" id="submit">Submit</button>
			</div>
		</div>
	</div>
	<script src="<?php echo asset('/js/app.js'); ?>"></script>
</body>
</html>